### ISSUE TITLE
Add a button for downloading the airway prediction in NIfTI format

### ISSUE THREAD

**Issue by tonycwk** [raidionics/AeroPath#58]
The airway prediction in NIfTI format is useful for model performance evaluation.

The current application produces the airway prediction in NIfTI format, however, it is not accessible through the web interface.

Therefore, it is very useful to add a button for downloading this file.

**Comment by andreped** [comment]
Thanks for the great suggestion, @tonycwk! :]

I can add support for this feature now. Will let you know when the PR has been merged.

**Comment by andreped** [comment]
@tonycwk Demo should down have a download button. You will need till inference is completely finished, before clicking download.

Test the updated deployment at:
https://huggingface.co/spaces/andreped/AeroPath

**Comment by andreped** [comment]
@tonycwk Sadly, there is a bug with Docker build. So deployment on Hugging Face is now broken.

This was because I upgraded Gradio to the latest version in the aforementioned PR.

I will make a bugfix for this now!
